export const METRIC_LABELS: Record<string, string> = {
  "API Documentation Index (ADI)": "Индекс документации API.",
  "API Exception Specificity Index (AESI)": "Доля типизированных выбрасываний ошибок.",
  "API Method Grouping Index (AMGI)": "Индекс группировки методов API.",
  "API Method Name Overloading Index (AMNOI)": "Индекс перегрузки методов API.",
  "API Parameter List Complexity Index (APXI)": "Индекс сложности списков параметров API.",
  "API Parameter List Consistency Index (APLCI)": "Индекс согласованности списков параметров API.",
  "API Thread Safety Index (ATSI)": "Индекс потокобезопасности API.",
  "Async Usage Total (ASYNC USAGE total)": "Общее использование асинхронности.",
  "Async Usage per Lines of Code (ASYNC USAGE per LOC)":
    "Использование асинхронности на строку кода.",
  "Average Function Size (LOC/function)": "Средний размер функции.",
  COG_COMPLEX_VUE: "Когнитивная сложность.",
  "Chain Length Maximum (CHAIN LENGTH max)": "Максимальная длина цепочки вызовов или обращений.",
  "Cognitive Complexity": "Когнитивная сложность.",
  "Complex Methods Count": "Количество сложных методов.",
  "Cyclomatic Complexity (avg)": "Средняя цикломатическая сложность.",
  "Cyclomatic Complexity (sum)": "Суммарная цикломатическая сложность.",
  DOM_CALLS_VUE: "Прямые обращения к DOM.",
  "Dead Code Count": "Количество мёртвого кода.",
  "Discriminated Unions Share (Disc Unions share)": "Доля дискриминируемых объединений.",
  "ESLint Errors Count": "Количество ошибок ESLint.",
  "ESLint Warnings Count": "Количество предупреждений ESLint.",
  "Explicit Any Count": "Количество явных any.",
  "Explicit Unknown Count": "Количество явных unknown.",
  FORCE_UPDATE_VUE: "Принудительные обновления Vue.",
  "Files Count": "Количество файлов.",
  "Functions Count (all)": "Общее количество функций.",
  "Functions Count (user)": "Количество пользовательских функций.",
  "Generic Precision Score": "Оценка точности generic-типов.",
  "Halstead Difficulty": "Трудность Холстеда.",
  "Halstead Effort": "Усилие Холстеда.",
  "Halstead Volume": "Объём Холстеда.",
  "Implicit Any Count": "Количество неявных any.",
  "Internal Similarity (%)": "Дублирование кода в процентах.",
  "Lines of Code (LOC)": "Количество строк кода.",
  "Long Message Chains Count": "Количество длинных цепочек обращений.",
  "Long Methods Count": "Количество длинных методов.",
  "Long Parameter List Count": "Количество длинных списков параметров.",
  "Long Scope Chaining Count": "Количество длинных цепочек областей видимости.",
  Maintainability: "Сопровождаемость.",
  "Max Parameters per Function": "Максимальное число параметров функции.",
  "Maximum Nesting Depth": "Максимальная глубина вложенности.",
  "Method Lines of Code Average (MLOC avg)": "Средний размер метода или функции.",
  "Method Lines of Code Maximum (MLOC max)": "Максимальный размер метода или функции.",
  REF_OBJARR_VUE: "ref для object или array.",
  SMELL_MUT_PROPS: "Мутация props.",
  SMELL_PROPS_REACT_LOSS: "Потеря реактивности props.",
  SMELL_VFOR_NOKEY: "v-for без key.",
  SMELL_VHTML: "Использование v-html.",
  "Strict Enabled": "Включён строгий режим TypeScript.",
  "Switch Without Default Count": "Количество операторов switch без default.",
  TS_ANY_VUE: "Использования any в TypeScript.",
  "Type Assertions Count": "Количество утверждений типов.",
  "Typed Error Handling Score": "Оценка типизированной обработки ошибок.",
  "AESI (typed throws ratio)": "Доля типизированных выбрасываний ошибок.",
  "AMNOI (перегрузки функций)": "Индекс перегрузки методов API.",
  "ASYNC_USAGE per LOC": "Использование асинхронности на строку кода.",
  "ASYNC_USAGE total (async function + await + then/catch/finally + new Promise)":
    "Общее использование асинхронности.",
  "CHAIN_LENGTH max (длинные цепочки вызовов/обращений)":
    "Максимальная длина цепочки вызовов или обращений.",
  "Discriminated Unions share (Tagged Union)": "Доля дискриминируемых объединений.",
  "Files count analyzed": "Количество проанализированных файлов.",
  "Generic Precision score": "Оценка точности generic-типов.",
  LOC: "Количество строк кода.",
  "MLOC avg": "Средний размер метода или функции.",
  "MLOC max": "Максимальный размер метода или функции.",
  "Typed Error Handling score": "Оценка типизированной обработки ошибок.",
  "explicit any count": "Количество явных any.",
  "explicit unknown count": "Количество явных unknown.",
  "implicit any count (diagnostics)": "Количество неявных any.",
  "strict enabled": "Включён строгий режим TypeScript.",
  "type assertions count (as/<T>)": "Количество утверждений типов.",
  "Undeclared Variables Count": "Количество необъявленных переменных.",
  "Unused Parameters Count": "Количество неиспользуемых параметров.",
  "Unused Variables Count": "Количество неиспользуемых переменных.",
  VMD_BIG_VIF: "Большие условия v-if.",
  VMD_BIG_VSHOW: "Большие условия v-show.",
  VMD_CC: "Цикломатическая сложность.",
  VMD_COMMENTS: "Количество комментариев.",
  VMD_COMP_SIDEFX: "Побочные эффекты в computed.",
  VMD_COMPL_COND: "Сложные условия.",
  VMD_DEEP_INDENT: "Глубокая вложенность.",
  VMD_ELSE: "Проблемные else-ветвления.",
  VMD_FN_SIZE: "Размер функций.",
  VMD_HTML_LINKS: "HTML-ссылки.",
  VMD_HUGE_FILES: "Большие файлы.",
  VMD_IF_NO_CURLY: "if без фигурных скобок.",
  VMD_IMG_ELEMS: "HTML-изображения.",
  VMD_MAGIC_NUM: "Магические числа.",
  VMD_NESTED_TERN: "Вложенный тернарный оператор.",
  VMD_NO_DOM: "Прямой доступ к DOM.",
  VMD_NO_IMPORTANT: "Использование !important.",
  VMD_NO_INLINE_STYLES: "Inline-стили.",
  VMD_NO_PROP_DESTR: "Деструктурирование props.",
  VMD_NO_SKIP_TESTS: "Пропущенные тесты.",
  VMD_NO_TS_LANG: "Отсутствие TypeScript.",
  VMD_NO_VAR: "Использование var.",
  VMD_PARAM_COUNT: "Число параметров.",
  VMD_PLAIN_SCRIPT: "Обычный script без TypeScript.",
  VMD_PROPS_DRILL: "Проброс props через цепочку компонентов.",
  VMD_REPEAT_CSS: "Повторяющийся CSS.",
  VMD_SCRIPT_LEN: "Длина script-блока.",
  VMD_SHORT_VAR: "Слишком короткие имена.",
  VMD_TOO_MANY_PROPS: "Слишком много props.",
  VMD_TOTAL_ISSUES: "Всего проблем VMD.",
  VMD_VFOR_EXPR: "Сложные выражения в v-for.",
  VMD_VFOR_IDX_KEY: "Индекс как key в v-for.",
  VMD_ZERO_LEN_CMP: "Сравнение с нулевой длиной.",
  VUEX_AVG_FN_SIZE: "Средний размер функции Vuex.",
  VUEX_CC_AVG: "Средняя цикломатическая сложность Vuex.",
  VUEX_CC_SUM: "Суммарная цикломатическая сложность Vuex.",
  VUEX_COG_COMPLEX: "Когнитивная сложность Vuex.",
  VUEX_DOM_CALLS: "Прямые обращения к DOM во Vuex.",
  VUEX_FILES: "Файлы Vuex.",
  VUEX_FNS_ALL: "Все функции Vuex.",
  VUEX_FNS_USER: "Пользовательские функции Vuex.",
  VUEX_FORCE_UPDATE: "Принудительные обновления Vuex.",
  VUEX_HAL_DIFF: "Трудность Холстеда Vuex.",
  VUEX_HAL_EFF: "Усилие Холстеда Vuex.",
  VUEX_HAL_VOL: "Объём Холстеда Vuex.",
  VUEX_LOC: "Строки кода Vuex.",
  VUEX_MAINT: "Сопровождаемость Vuex.",
  VUEX_NEST_MAX: "Максимальная глубина вложенности Vuex.",
  VUEX_PARAMS_MAX: "Максимальное число параметров Vuex.",
  VUEX_REF_OBJARR: "ref для object или array во Vuex.",
  VUEX_SIM_INT: "Внутреннее сходство Vuex.",
  VUEX_TS_ANY: "Тип any в TypeScript-коде Vuex.",
  active_days: "Число активных дней.",
  activeDays: "Число активных дней.",
  avg_declarations_per_rule_avg: "Среднее количество объявлений в правиле.",
  avg_font_size_bytes: "Средний размер файла шрифта.",
  avg_image_size_bytes: "Средний размер изображения.",
  avg_selector_complexity_overall: "Средняя сложность селектора.",
  avg_specificity_avg: "Средняя специфичность селекторов.",
  axe_critical: "Количество критических нарушений Axe.",
  axe_minor: "Количество незначительных нарушений Axe.",
  axe_moderate: "Количество умеренных нарушений Axe.",
  axe_serious: "Количество серьёзных нарушений Axe.",
  axe_violations_total: "Количество нарушений доступности Axe.",
  churn_ratio: "Доля переработки кода.",
  churnRatio: "Доля переработки кода.",
  code_churn: "Интенсивность изменения кода.",
  codeChurn: "Интенсивность изменения кода.",
  commitsVsChurn: "Коммиты и интенсивность изменения кода.",
  commitsVsChurnPct: "Коммиты и доля переработки кода.",
  complex_selectors_ratio_avg: "Доля сложных селекторов.",
  average_function_size: "Средний размер функции.",
  css_bytes_total: "Суммарный размер CSS-файлов.",
  css_files: "Количество CSS-файлов.",
  cognitive_complexity: "Когнитивная сложность.",
  complex_methods_count: "Количество сложных методов.",
  cyclomatic_complexity_avg: "Средняя цикломатическая сложность.",
  cyclomatic_complexity_sum: "Суммарная цикломатическая сложность.",
  dead_code_count: "Количество мёртвого кода.",
  development_duration_days: "Продолжительность разработки.",
  developmentDurationDays: "Продолжительность разработки.",
  dom_nodes_avg: "Среднее количество элементов дерева HTML.",
  dup_decl_ratio_avg: "Доля дублирующихся CSS-объявлений.",
  duplicate_id_values_total: "Количество повторяющихся значений id.",
  duplicate_ids_total: "Количество дублирующихся id.",
  font_bytes_total: "Суммарный размер шрифтов.",
  font_files_total: "Количество файлов шрифтов.",
  form_controls_missing_label_ratio: "Доля элементов формы без label.",
  form_controls_missing_label_total: "Количество элементов формы без label.",
  form_controls_total: "Количество элементов формы.",
  eslint_errors_count: "Количество ошибок ESLint.",
  eslint_warnings_count: "Количество предупреждений ESLint.",
  files_count: "Количество файлов.",
  functions_count_all: "Общее количество функций.",
  functions_count_user: "Количество пользовательских функций.",
  halstead_difficulty: "Трудность Холстеда.",
  halstead_effort: "Усилие Холстеда.",
  halstead_volume: "Объём Холстеда.",
  heading_order_violations_total: "Количество нарушений порядка заголовков.",
  html_bytes_total: "Суммарный размер HTML-файлов.",
  html_files: "Количество HTML-файлов.",
  image_bytes_total: "Суммарный размер изображений.",
  image_files_total: "Количество изображений.",
  img_missing_alt_ratio: "Доля изображений без alt.",
  img_missing_alt_total: "Количество изображений без alt.",
  img_total: "Количество изображений img.",
  import_count_total: "Количество директив @import.",
  inner_html_usage_count: "Количество использований innerHTML.",
  internal_similarity: "Дублирование кода в процентах.",
  max_declarations_per_rule_max: "Максимальное количество объявлений в правиле.",
  max_dom_depth_max: "Максимальная глубина элементов дерева HTML.",
  lines_of_code: "Количество строк кода.",
  long_message_chains_count: "Количество длинных цепочек обращений.",
  long_methods_count: "Количество длинных методов.",
  long_parameter_list_count: "Количество длинных списков параметров.",
  long_scope_chaining_count: "Количество длинных цепочек областей видимости.",
  maintainability: "Сопровождаемость.",
  max_selector_complexity_max: "Максимальная сложность селектора.",
  max_parameters_per_function: "Максимальное число параметров функции.",
  maximum_nesting_depth: "Максимальная глубина вложенности.",
  max_specificity_max: "Максимальная специфичность селектора.",
  meaningful_commit_count: "Количество содержательных коммитов.",
  meaningfulCommitCount: "Количество содержательных коммитов.",
  median_commit_size: "Медианный размер коммита.",
  medianCommitSize: "Медианный размер коммита.",
  night_commit_pct: "Доля ночных коммитов.",
  nightCommitPct: "Доля ночных коммитов.",
  nonsemantic_containers_total: "Количество несемантических контейнеров.",
  rules_total: "Количество CSS-правил.",
  selectors_total: "Количество CSS-селекторов.",
  semantic_element_usage_ratio_overall: "Общая доля использования семантических элементов.",
  semantic_elements_total: "Количество семантических элементов.",
  semantic_ratio_avg: "Средняя доля семантических элементов.",
  specificity_variance_overall: "Дисперсия специфичности селекторов.",
  switch_without_default_count: "Количество операторов switch без default.",
  total_commit_count: "Общее количество коммитов.",
  total_lines_added: "Суммарное количество добавленных строк.",
  total_lines_deleted: "Суммарное количество удалённых строк.",
  total_selector_complexity_total: "Суммарная сложность селекторов.",
  totalCommitCount: "Общее количество коммитов.",
  totalLinesAdded: "Суммарное количество добавленных строк.",
  totalLinesDeleted: "Суммарное количество удалённых строк.",
  unique_css_properties_avg: "Среднее количество уникальных CSS-свойств.",
  unique_css_properties_work: "Количество уникальных CSS-свойств.",
  undeclared_variables_count: "Количество необъявленных переменных.",
  unused_parameters_count: "Количество неиспользуемых параметров.",
  unused_variables_count: "Количество неиспользуемых переменных.",
  uses_avif: "Использование AVIF.",
  uses_webp: "Использование WebP.",
  vnu_errors_total: "Количество ошибок VNU.",
  vnu_files_checked: "Количество файлов, проверенных VNU.",
  vnu_unparsed_files: "Количество неразобранных файлов.",
  vnu_warnings_total: "Количество предупреждений VNU."
}

export const getMetricLabel = (metric: string): string => {
  const label = METRIC_LABELS[metric] || metric

  return label.endsWith(".") ? label.slice(0, -1) : label
}
